version: "3.8"
services:
  doardigital_db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db_setup.sql:/docker-entrypoint-initdb.d/setup.sql

  doardigital_api:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: doardigital_db
      DB_PORT: 5432
      DB_NAME: db
      PORT: 3000
      JWT_KEY: 123
      JWT_EXPIRATION: 1h
    depends_on:
      - doardigital_db
    ports:
      - "80:3000"
    volumes:
      - ./src/:/usr/src/app
