version: "3.8"
services:
  doardigital_db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "80:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db_setup.sql:/docker-entrypoint-initdb.d/setup.sql
